version: 0.2

phases:
    pre_build:
        commands:
            - echo Installing packages...
            - yum install -y nodejs
            - npm install
    build:
        commands:
          - echo Building app...
          - npm run build
    post_build:
        commands:
          - echo Uploading app to S3...